### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by bernardojedi** [Seedstars/django-react-redux-jwt-base#18]
I had this error on Google Chrome (similar on firefox) when following readme:

`
Fetch API cannot load http://localhost:8000/api/v1/accounts/login/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

I had to install `django-cors-middleware` and append these lines to `djangoreactredux.settings.dev` to be able to make it work:

```python
INSTALLED_APPS += ('corsheaders',)

MIDDLEWARE_CLASSES += (
    'corsheaders.middleware.CorsMiddleware',
    )

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
```

Since I don't have much experience with git, maybe someone wants to make a PR.

*Loved the example by the way!

**Comment by bernardojedi** [comment]
#19 
Learned something today.

**Comment by lfrodrigues** [comment]
This way of working is not a bug is a feature. You are suposed to configure in 
```/src/static/utils/config.js``` the url of the backend. 

The our example we have: 
```export const SERVER_URL = 'http://localhost:8000';```.

If you write ```http://localhost:8000``` in your browser instead of ```http://127.0.0.1:8000```  everything should work fine.
