### ISSUE TITLE
sessionStorage over localStorage

### ISSUE THREAD

**Issue by dopeboy** [Seedstars/django-react-redux-jwt-base#21]
I noticed in src/static/actions/auth.js that sessionStorage is being used over localStorage. Wouldn't typical behavior be to persist a user's session even when the browser gets closed? 

Happy to submit a PR - just wanted to know if there's a rationale I'm missing.

**Comment by lfrodrigues** [comment]
Ideally you should not leave an account logged in after user closes browser/turns off computer as it increases your attack surface.

In your personal projects you can do it but at Seedstars we don't.

Thanks!
