### ISSUE TITLE
Serializer class should not be a tuple in APIView

### ISSUE THREAD

**Issue by akarambir** [Seedstars/django-react-redux-jwt-base#3]
In the Account views, the serializer class is denoted as empty tuple(Line 54 and 73). It should either be a proper serilizer class or `None`.

[Here](https://github.com/Seedstars/django-react-redux-jwt-base/blob/master/src/accounts/views.py)

**Comment by pedrorodriguesgomes** [comment]
Thank you for your comment. There are several approaches on how to do this, several packages declare as an empty tuple. We will review it and update accordingly.

**Comment by pedrorodriguesgomes** [comment]
Views updated, thank you.

**Comment by akarambir** [comment]
:+1:
