### ISSUE TITLE
Are there plans to support server side rendering of react components

### ISSUE THREAD

**Issue by epicallan** [Seedstars/django-react-redux-jwt-base#7]

**Comment by pedrorodriguesgomes** [comment]
Thank you for your comment. For this boilerplate project we aren't planning to support server side rendering or react components. In the future, we may support if we see that we have an use case for it.

**Comment by lfrodrigues** [comment]
I'm closing this as we will not support server side rendering.  See facebook react conf, they also don't suggest doing it.
